### ISSUE TITLE
Missing libjllama on Linux aarch64

### ISSUE THREAD

**Issue by AutonomicPerfectionist** [kherud/java-llama.cpp#17]
I have not had the time to test the arm variant yet but I took a look at the generated maven artifact and noticed the aarch64 platform is missing the libjllama.so library, I assume this would cause problems

**Comment by AutonomicPerfectionist** [comment]
Appears the latest workflow run silently failed during compilation, a syntax error in llama.cpp's common/common.cpp

Might be an upstream problem, but at the very least the workflow should probably be adjusted to correctly fail on compilation issues

**Comment by ashwanthkumar** [comment]
Just adding that it's the same issue for Mac as well. aarch64 is missing on the latest release.

**Comment by kherud** [comment]
You're right, both macos and linux aarch64 files are incomplete. I added some unit tests that should be run during the workflow to validate everything works. This doesn't work yet, since I need a model file in the github runner. 
Maybe a model could be downloaded for example from huggingface hub. But I think I saw some repos that had tiny testing models. Those could be directly added to the repository. Another solution might be to add a minimal test that just tries to load the library. I'll find a solution for the next release.
