### ISSUE TITLE
[Feature Request] Bundle compiled CPU-only libs into jar

### ISSUE THREAD

**Issue by AutonomicPerfectionist** [kherud/java-llama.cpp#2]
Is it possible to use Github Actions to compile the llama.cpp libraries for CPU-only inference (to avoid needing multiple different variants per architecture and to avoid build dep issues in Actions) and include them in the built jar? [This project](https://github.com/GiviMAD/whisper-jni/tree/main) has a workflow that can be used to build off of. They use JNI instead of JNA, but the same methods should be usable. The resource folders containing the architecture-specific libraries need to be named a certain way though for JNA to find them: `{os-name}-{arch}`. The docs aren't super helpful on that, they imply on linux it should be `linux-amd64` but I could only get it to work by naming the resource folder `linux-x86-64`

I can help with this if you would like, but I can't test the workflow myself for obvious reasons

**Comment by kherud** [comment]
I have used a similar approach in the past using JNI (inspired by [sqlite-jdbc](https://github.com/xerial/sqlite-jdbc) back then), but decided against it for this project, since there are just too many ways to compile the library.

I am no C/C++ developer, but I think the bare minimum just for CPU inference is one for each combination of:
- linux, macos, windows (ignoring stuff like openbsd, android, etc.)
- x86_64, arm64 (ignoring 32 bit systems)
And then there are a bunch of combinations for GPU acceleration and potentially other custom build options.

That's why I didn't want to inflate the jar unnecessarily, since the risk of not supporting any particular system is too high anyway.

On the other hand, llama.cpp is really easy to build, so it shouldn't be too hard to setup a GitHub action. It would also greatly simplify the use of the library. The best option would be if there was a way to deliver platform-specific artifacts via Maven. But I don't think that's possible.

> The resource folders containing the architecture-specific libraries need to be named a certain way though for JNA to find them: {os-name}-{arch}. The docs aren't super helpful on that, they imply on linux it should be linux-amd64 but I could only get it to work by naming the resource folder linux-x86-64

I think the approach is to use a helper class which decides which library to load. For whisper-jni this can be found here:
- https://github.com/GiviMAD/whisper-jni/blob/7f2a2532fc21cc6b4887977c14e7fafd9d655f08/src/main/java/io/github/givimad/whisperjni/internal/NativeUtils.java
- https://github.com/GiviMAD/whisper-jni/blob/7f2a2532fc21cc6b4887977c14e7fafd9d655f08/src/main/java/io/github/givimad/whisperjni/WhisperJNI.java#L247

JNA even has a class built in for this as far as I know.

**Comment by AutonomicPerfectionist** [comment]
> The best option would be if there was a way to deliver platform-specific artifacts via Maven. But I don't think that's possible.

The JavaCPP project uses Maven Classifiers to differentiate between platform-specific artifacts, so by default maven will pull in all platform artifacts but users are free to select specific ones to pull in. That does add significant complexity to the build process though.

> JNA even has a class built in for this as far as I know.

Yep, it automatically searches the library and class paths for the requested library, either at the root of one of those paths, or under a platform-specific directory. So to get the platform detection for linux working, all I had to do was put the `libllama.so` in a resource folder called `linux-x86-64`, JNA found it automatically and loaded it, no need to use a helper class like you would with JNI

**Comment by kherud** [comment]
Ok, it is probably a good compromise to at least provide libraries for CPU inference and all major platforms, with a note in the readme for further GPU support.

I've never set up a GitHub action for this before. If you know about it, I'd appreciate the help, otherwise I'll take a look over the next few days.

**Comment by AutonomicPerfectionist** [comment]
I can try to help, yeah. I think starting with a base workflow from the JNI bindings for whisper.cpp would be a good idea:

https://github.com/GiviMAD/whisper-jni/blob/7f2a2532fc21cc6b4887977c14e7fafd9d655f08/.github/workflows/main.yml

I see you already have build scripts for linux and Mac, we'll need one for windows as well. From there, we need to modify the build scripts to place the built libraries in the proper resource directories and then make the workflow use those scripts. I'll do a bit of work on my end and see if I can come up with anything.
